version: '3.8' # استخدم إصدار مدعوم

services:
  postgres:
    image: postgres:15
    container_name: fx_deals_postgres
    environment:
      POSTGRES_DB: fx_deals
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0795798860
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  fx-deals-service:
    build: .
    container_name: fx_deals_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fx_deals
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

    command: >
      sh -c "sleep 30 && java -jar app.jar"

volumes:
  postgres_data: